[features]
seeds = false
[programs.devnet]
switchboard_vrf_flip = "DX51kwewcbkZgAd9QcCcmA7QkLeRoRUucfxmbHCEa92W"
[programs.mainnet]
switchboard_vrf_flip = "DX51kwewcbkZgAd9QcCcmA7QkLeRoRUucfxmbHCEa92W"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
# wallet = "../payer-keypair.json"
cluster = "devnet"
wallet = "./user.json"

[scripts]
test = "npx mocha --extension ts --require ts-node/register -t 1000000 tests/**/*.test.ts"
